/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Atm;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Victus
 */
public class AtmMachineDemo extends javax.swing.JFrame {
int count = 0;
    /**
     * Creates new form AtmMachineDemo
     */
    public AtmMachineDemo() {
        initComponents();
    }
    
    private void switchToPanel(String panelName) {
        CardLayout cardLayout = (CardLayout) mainpanel.getLayout();
        cardLayout.show(mainpanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        cardpanel = new javax.swing.JPanel();
        cn = new javax.swing.JLabel();
        cn1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Pinpanel = new javax.swing.JPanel();
        jbutton2 = new javax.swing.JButton();
        pn = new javax.swing.JLabel();
        pn1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label1.setForeground(new java.awt.Color(153, 0, 153));
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("Welcome to Prime Commerical Bank");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        mainpanel.setLayout(new java.awt.CardLayout());

        cn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cn.setText("Card Number :");

        cn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardpanelLayout = new javax.swing.GroupLayout(cardpanel);
        cardpanel.setLayout(cardpanelLayout);
        cardpanelLayout.setHorizontalGroup(
            cardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardpanelLayout.createSequentialGroup()
                .addGroup(cardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardpanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(cn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cn1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardpanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        cardpanelLayout.setVerticalGroup(
            cardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardpanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        mainpanel.add(cardpanel, "card2");

        jbutton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbutton2.setText("Submit");
        jbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton2ActionPerformed(evt);
            }
        });

        pn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pn.setText("Pin Number :");

        pn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout PinpanelLayout = new javax.swing.GroupLayout(Pinpanel);
        Pinpanel.setLayout(PinpanelLayout);
        PinpanelLayout.setHorizontalGroup(
            PinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinpanelLayout.createSequentialGroup()
                .addGroup(PinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PinpanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PinpanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(pn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        PinpanelLayout.setVerticalGroup(
            PinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinpanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(PinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        mainpanel.add(Pinpanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        DBConnection db = new DBConnection();
        Connection conn = db.getConnection();
        try {
            Statement stat = conn.createStatement();
            String sql = "SELECT card_number FROM record";
            ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                int card = rs.getInt("card_number");
                String cardNumber = cn1.getText();
                int CardNum = Integer.parseInt(cardNumber);
                if (CardNum == card) {
                    switchToPanel("card3");
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Card Number!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No Record Found!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid card Number!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid card Number!");
        }
         cn1.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton2ActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        Connection conn = db.getConnection();
        try {
            Statement stat = conn.createStatement();
            String sql = "SELECT card_number,pin_number, status FROM record";
            ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                int card = rs.getInt("card_number");
                int pin = rs.getInt("pin_number");
                int status = rs.getInt("status");
                int maxAttempts = 3;
                if (status == 0) {

                    String pinNumber = pn1.getText();
                    int PinNum = Integer.parseInt(pinNumber);
                    if (PinNum == pin) {
                        operation op = new operation();
                        op.setVisible(true);
                        dispose();
                    } else if (PinNum != pin) {
                        count++;
                        if (count == maxAttempts) {
                            String blockCard = "UPDATE record SET status=1 WHERE card_number= '" + card + "'";
                            stat.executeUpdate(blockCard);
                            JOptionPane.showMessageDialog(null, "Your card has been blocked. Please contact your respective Bank.");
                        } else {
                            JPanel panel = new JPanel();
                            panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

                            JLabel messageLabel1 = new JLabel("Invalid PIN!");
                            JLabel messageLabel2 = new JLabel("Remaining Attempt:" + (maxAttempts - count));

                            panel.add(messageLabel1);
                            panel.add(messageLabel2);

                            JOptionPane.showMessageDialog(null, panel, "Two Messages", JOptionPane.INFORMATION_MESSAGE);

                        }
                        pn1.setText("");

                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid PIN!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Your card has been blocked. Please contact your respective Bank.");
                    jbutton2.setEnabled(false);
                    pn1.setText("");
                }

            } else {
                JOptionPane.showMessageDialog(null, "No Record Found!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please insert Valid Number.");
        }


    }//GEN-LAST:event_jbutton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtmMachineDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtmMachineDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtmMachineDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtmMachineDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtmMachineDemo().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JPanel Pinpanel;
    private javax.swing.JPanel cardpanel;
    private javax.swing.JLabel cn;
    private javax.swing.JTextField cn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutton2;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel pn;
    private javax.swing.JTextField pn1;
    // End of variables declaration//GEN-END:variables
}
