/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Atm;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Victus
 */
public class operation extends javax.swing.JFrame {

    /**
     * Creates new form operation
     */
    public operation() {
        initComponents();
    }
    
    private void switchToPanel(String panelName) {
        CardLayout cardLayout = (CardLayout) menupanel.getLayout();
        cardLayout.show(menupanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menupanel = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        enquiry = new javax.swing.JButton();
        Deposit = new javax.swing.JButton();
        ChangePin = new javax.swing.JButton();
        MiniStatement = new javax.swing.JButton();
        cashOut = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        balanceDisplay = new javax.swing.JPanel();
        BalanceText = new javax.swing.JLabel();
        DisplayBalance = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        CashOutPanel = new javax.swing.JPanel();
        cashoutText = new javax.swing.JLabel();
        CashOutfield = new javax.swing.JTextField();
        CashOutButton = new javax.swing.JButton();
        CashOutBackButton = new javax.swing.JButton();
        ChangePinPanel = new javax.swing.JPanel();
        oldLabel = new javax.swing.JLabel();
        OldField = new javax.swing.JTextField();
        oldLabel2 = new javax.swing.JLabel();
        NewField = new javax.swing.JTextField();
        oldLabel1 = new javax.swing.JLabel();
        RePinField = new javax.swing.JTextField();
        ChangeButton = new javax.swing.JButton();
        ChangeButton1 = new javax.swing.JButton();
        DepositPanel = new javax.swing.JPanel();
        depoLabel = new javax.swing.JLabel();
        DepoField = new javax.swing.JTextField();
        DepoButton = new javax.swing.JButton();
        DepoBackButton = new javax.swing.JButton();
        MiniStatementPanel = new javax.swing.JPanel();
        MiniLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        MiniBackButton = new javax.swing.JButton();
        ShowButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Prime Commerical Bank");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        javax.swing.GroupLayout titlepanelLayout = new javax.swing.GroupLayout(titlepanel);
        titlepanel.setLayout(titlepanelLayout);
        titlepanelLayout.setHorizontalGroup(
            titlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(titlepanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        titlepanelLayout.setVerticalGroup(
            titlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlepanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        menupanel.setLayout(new java.awt.CardLayout());

        enquiry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enquiry.setText("Balance Enquiry");
        enquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enquiryActionPerformed(evt);
            }
        });

        Deposit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Deposit.setText("Deposit");
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });

        ChangePin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChangePin.setText("Change PIN");
        ChangePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePinActionPerformed(evt);
            }
        });

        MiniStatement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MiniStatement.setText("Mini-Statement");
        MiniStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiniStatementActionPerformed(evt);
            }
        });

        cashOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cashOut.setText("Cash Out");
        cashOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashOutActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please Select Transactions :");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enquiry)
                            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ChangePin, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(Deposit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MiniStatement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cashOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53))))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiniStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashOut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangePin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        menupanel.add(menu, "card2");

        BalanceText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BalanceText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BalanceText.setText("Your Balance is :");

        DisplayBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackButton.setText("OK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout balanceDisplayLayout = new javax.swing.GroupLayout(balanceDisplay);
        balanceDisplay.setLayout(balanceDisplayLayout);
        balanceDisplayLayout.setHorizontalGroup(
            balanceDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceDisplayLayout.createSequentialGroup()
                .addGroup(balanceDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balanceDisplayLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(BalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(balanceDisplayLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(DisplayBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(balanceDisplayLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        balanceDisplayLayout.setVerticalGroup(
            balanceDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceDisplayLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DisplayBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        menupanel.add(balanceDisplay, "card3");

        cashoutText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cashoutText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashoutText.setText("Enter the Amount You want Withdraw :");

        CashOutfield.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        CashOutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CashOutButton.setText("Submit");
        CashOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashOutButtonActionPerformed(evt);
            }
        });

        CashOutBackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CashOutBackButton.setText("Back");
        CashOutBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashOutBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CashOutPanelLayout = new javax.swing.GroupLayout(CashOutPanel);
        CashOutPanel.setLayout(CashOutPanelLayout);
        CashOutPanelLayout.setHorizontalGroup(
            CashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CashOutPanelLayout.createSequentialGroup()
                .addGroup(CashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CashOutPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cashoutText, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CashOutPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(CashOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(CashOutBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CashOutPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(CashOutfield, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        CashOutPanelLayout.setVerticalGroup(
            CashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CashOutPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cashoutText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CashOutfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(CashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CashOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CashOutBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        menupanel.add(CashOutPanel, "card4");

        oldLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oldLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oldLabel.setText("Enter your New PIN :");

        OldField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        oldLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oldLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oldLabel2.setText("Enter your Old PIN :");

        NewField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        oldLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oldLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oldLabel1.setText("Re-Enter Your New PIN :");

        RePinField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        ChangeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ChangeButton.setText("Change");
        ChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeButtonActionPerformed(evt);
            }
        });

        ChangeButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ChangeButton1.setText("Back");
        ChangeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChangePinPanelLayout = new javax.swing.GroupLayout(ChangePinPanel);
        ChangePinPanel.setLayout(ChangePinPanelLayout);
        ChangePinPanelLayout.setHorizontalGroup(
            ChangePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePinPanelLayout.createSequentialGroup()
                .addGroup(ChangePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePinPanelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(OldField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChangePinPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(NewField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChangePinPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(ChangePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ChangePinPanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(RePinField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChangePinPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(ChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChangePinPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(oldLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        ChangePinPanelLayout.setVerticalGroup(
            ChangePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oldLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OldField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RePinField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ChangePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menupanel.add(ChangePinPanel, "card5");

        depoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        depoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depoLabel.setText("Enter the Amount You want to Deposit :");

        DepoField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        DepoButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DepoButton.setText("Deposit");
        DepoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepoButtonActionPerformed(evt);
            }
        });

        DepoBackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DepoBackButton.setText("Back");
        DepoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DepositPanelLayout = new javax.swing.GroupLayout(DepositPanel);
        DepositPanel.setLayout(DepositPanelLayout);
        DepositPanelLayout.setHorizontalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositPanelLayout.createSequentialGroup()
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(depoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DepositPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DepositPanelLayout.createSequentialGroup()
                                .addComponent(DepoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DepoBackButton))
                            .addComponent(DepoField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        DepositPanelLayout.setVerticalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(depoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DepoField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        menupanel.add(DepositPanel, "card6");

        MiniLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MiniLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MiniLabel.setText("Mini-Statement of Your Account :");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Card Number", "Description", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("id");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("Card Number");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Description");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Date");
            jTable2.getColumnModel().getColumn(4).setHeaderValue("Amount");
        }

        MiniBackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MiniBackButton.setText("Back");
        MiniBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiniBackButtonActionPerformed(evt);
            }
        });

        ShowButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ShowButton.setText("Show statement");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MiniStatementPanelLayout = new javax.swing.GroupLayout(MiniStatementPanel);
        MiniStatementPanel.setLayout(MiniStatementPanelLayout);
        MiniStatementPanelLayout.setHorizontalGroup(
            MiniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniStatementPanelLayout.createSequentialGroup()
                .addGroup(MiniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiniStatementPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(MiniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MiniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MiniStatementPanelLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(ShowButton)
                            .addGap(18, 18, 18)
                            .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MiniBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MiniStatementPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        MiniStatementPanelLayout.setVerticalGroup(
            MiniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniStatementPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(MiniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MiniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MiniBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(215, 215, 215))
        );

        menupanel.add(MiniStatementPanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enquiryActionPerformed
        // TODO add your handling code here:
        switchToPanel("card3");
        DBConnection db = new DBConnection();
        Connection conn = db.getConnection();
        try {
            Statement stat = conn.createStatement();
            String sql = "SELECT balance FROM transaction ORDER BY date DESC LIMIT 1";
            ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                double balance = rs.getDouble("balance");
                DisplayBalance.setText(Double.toString(balance));
                //System.out.println("Your account balance is: " +balance);
            } else {
                JOptionPane.showMessageDialog(null, "No Record Found!");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_enquiryActionPerformed

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        // TODO add your handling code here:
        switchToPanel("card6");
    }//GEN-LAST:event_DepositActionPerformed

    private void ChangePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePinActionPerformed
        // TODO add your handling code here:
        switchToPanel("card5");
    }//GEN-LAST:event_ChangePinActionPerformed

    private void MiniStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiniStatementActionPerformed
        // TODO add your handling code here:
        switchToPanel("card7");
    }//GEN-LAST:event_MiniStatementActionPerformed

    private void cashOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashOutActionPerformed
        // TODO add your handling code here:
        switchToPanel("card4");
    }//GEN-LAST:event_cashOutActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void CashOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashOutButtonActionPerformed
        // TODO add your handling code here:
         DBConnection db = new DBConnection();
        Connection conn = db.getConnection();
        try{
        String withdraw = CashOutfield.getText();
        Double Withdraw = Double.parseDouble(withdraw);
        if(Withdraw % 500==0){
        Statement stat = conn.createStatement();
        String sql = "SELECT balance, card_number, deposit, description, amount FROM transaction ORDER BY date DESC LIMIT 1";
	ResultSet rs = stat.executeQuery(sql);
	if (rs.next()){
            double balance = rs.getDouble("balance");
            int card=rs.getInt("card_number");
            double deposit = rs.getDouble("deposit");
            String description = rs.getString("description");
            double amount = rs.getDouble("amount"); 
            if(balance >= Withdraw){
                balance =balance - Withdraw;
                String des ="Withdraw operation";
                String updateQuery ="UPDATE transaction SET withdraw="+Withdraw+" WHERE card_number= '" +card+ "' ORDER BY date DESC LIMIT 1";
                LocalDateTime withdrawDateTime = LocalDateTime.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                String formattedDateTime = withdrawDateTime.format(formatter);
		stat.executeUpdate(updateQuery);		
                String insertQuery = "INSERT INTO transaction(card_number,balance,withdraw,deposit,date,description,amount) VALUES('"+card+"', '"+balance+"', '"+Withdraw+"', '"+deposit+"', '"+formattedDateTime+"', '"+des+"', '"+Withdraw+"')";
                stat.executeUpdate(insertQuery);
                JOptionPane.showMessageDialog(null,"Withdrawal Amount Successful: " + Withdraw);    
            }else{
            JOptionPane.showMessageDialog(null,"Insufficient Funds!");    
            }
        }else{
           JOptionPane.showMessageDialog(null,"No Record Found!");                                   
           }
        }else{
        JOptionPane.showMessageDialog(null, "Withdraw amount should be 500 or Multiple of it.");
        }
        //CashOutfield.setText("");
        }catch(SQLException e){
            e.printStackTrace();
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Amount should be valid number.");
        }
        CashOutfield.setText("");
    }//GEN-LAST:event_CashOutButtonActionPerformed

    private void ChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeButtonActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        Connection conn = db.getConnection();
        try {
            Statement stat = conn.createStatement();
            String sql = "SELECT pin_number, card_number FROM record";
            ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                int card = rs.getInt("card_number");
                int PIN = rs.getInt("pin_number");
                String CurrentPin = OldField.getText();
                int currentPin = Integer.parseInt(CurrentPin);
                if (currentPin == PIN) {
                    String NewPin = NewField.getText();
                    int newPin = Integer.parseInt(NewPin);
                    String RePin = RePinField.getText();
                    int rePin = Integer.parseInt(RePin);
                    if (newPin == rePin) {
                        PIN = rePin;
                        String qls = "UPDATE record SET pin_number=" + rePin + " WHERE card_number= '" + card + "'";
                        stat.executeUpdate(qls);
                        JOptionPane.showMessageDialog(null, "PIN changed successfully!");
                    } else {

                        JOptionPane.showMessageDialog(null, "PIN confirmation failed. Please try Again.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Old PIN not matched!");
                }

            } else {
                JOptionPane.showMessageDialog(null,"No Records Found!");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "PIN should be valid Number.");
        }
        OldField.setText("");
        NewField.setText("");
        RePinField.setText("");
    }//GEN-LAST:event_ChangeButtonActionPerformed

    private void DepoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepoButtonActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        Connection conn = db.getConnection();
        try {
            String Deposit = DepoField.getText();
            double deposit = Double.parseDouble(Deposit);
            if (deposit % 500 == 0) {
                Statement stat = conn.createStatement();
                String sql = "SELECT card_number, balance, withdraw, description, amount FROM transaction ORDER BY date DESC LIMIT 1";
                ResultSet rs = stat.executeQuery(sql);
                if (rs.next()) {
                    int card = rs.getInt("card_number");
                    double balance = rs.getDouble("balance");
                    double withdraw = rs.getDouble("withdraw");
                    String description = rs.getString("description");
                    double amount = rs.getDouble("amount");
                    balance = balance + deposit;

                    String desc = "Deposit Operation";

                    LocalDateTime withdrawDateTime = LocalDateTime.now();
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                    String formattedDateTime = withdrawDateTime.format(formatter);

                    String insertQuery = "INSERT INTO transaction(card_number,balance,withdraw,deposit,date,description,amount) VALUES('" + card + "', '" + balance + "', '" + withdraw + "','" + deposit + "', '" + formattedDateTime + "', '" + desc + "', '" + deposit + "')";
                    stat.executeUpdate(insertQuery);
                    //DepoField.setText("");
                    JOptionPane.showMessageDialog(null, "Cash Deposited Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "No Records Found!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Deposit amount should be 500 or Multiple of it.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Amount should be valid Number.");
        }
        DepoField.setText("");
    }//GEN-LAST:event_DepoButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
      switchToPanel("card2");
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CashOutBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashOutBackButtonActionPerformed
        // TODO add your handling code here:
        switchToPanel("card2");
    }//GEN-LAST:event_CashOutBackButtonActionPerformed

    private void DepoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepoBackButtonActionPerformed
        // TODO add your handling code here:
        switchToPanel("card2");
    }//GEN-LAST:event_DepoBackButtonActionPerformed

    private void ChangeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeButton1ActionPerformed
        // TODO add your handling code here:
        switchToPanel("card2");
    }//GEN-LAST:event_ChangeButton1ActionPerformed

    private void MiniBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiniBackButtonActionPerformed
        // TODO add your handling code here:
        switchToPanel("card2");
    }//GEN-LAST:event_MiniBackButtonActionPerformed

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        Connection conn = db.getConnection();
        try{
        Statement stat = conn.createStatement();
	//String sql = "SELECT name FROM records WHERE card_number= '"+card+"'";
	    String sql = "SELECT id, card_number, date, description, amount FROM transaction LIMIT 10";
            ResultSet rs = stat.executeQuery(sql);
            //double balance = 0.0;
            while (rs.next()) {
                String id = String.valueOf(rs.getInt("id"));
                String card = String.valueOf(rs.getInt("card_number"));
                String des = rs.getString("description");
                String date = rs.getString("date");
                String amount = String.valueOf(rs.getInt("amount"));

                String tbData[] = {id, card, des, date, amount};
                DefaultTableModel tblModel = (DefaultTableModel) jTable2.getModel();
                tblModel.addRow(tbData);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL Error!");
        }
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable2.getModel();
        tblModel.setRowCount(0);
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BalanceText;
    private javax.swing.JButton CashOutBackButton;
    private javax.swing.JButton CashOutButton;
    private javax.swing.JPanel CashOutPanel;
    private javax.swing.JTextField CashOutfield;
    private javax.swing.JButton ChangeButton;
    private javax.swing.JButton ChangeButton1;
    private javax.swing.JButton ChangePin;
    private javax.swing.JPanel ChangePinPanel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DepoBackButton;
    private javax.swing.JButton DepoButton;
    private javax.swing.JTextField DepoField;
    private javax.swing.JButton Deposit;
    private javax.swing.JPanel DepositPanel;
    private javax.swing.JTextField DisplayBalance;
    private javax.swing.JButton Exit;
    private javax.swing.JButton MiniBackButton;
    private javax.swing.JLabel MiniLabel;
    private javax.swing.JButton MiniStatement;
    private javax.swing.JPanel MiniStatementPanel;
    private javax.swing.JTextField NewField;
    private javax.swing.JTextField OldField;
    private javax.swing.JTextField RePinField;
    private javax.swing.JButton ShowButton;
    private javax.swing.JPanel balanceDisplay;
    private javax.swing.JButton cashOut;
    private javax.swing.JLabel cashoutText;
    private javax.swing.JLabel depoLabel;
    private javax.swing.JButton enquiry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menupanel;
    private javax.swing.JLabel oldLabel;
    private javax.swing.JLabel oldLabel1;
    private javax.swing.JLabel oldLabel2;
    private javax.swing.JPanel titlepanel;
    // End of variables declaration//GEN-END:variables
}
